- design-doctorine.md
Update design doctorine based on 2022-03-17. @MariekeSpanFurore coud you add notes you took from your Q's here as well?
> Update design doctorine based on 2022-03-17

- design-doctorine.md
Here are some of my notes for in the design doctrine.
> Update on design doctorine

- input/pagecontent/4_security.md
- input/pagecontent/index.md
Hi Vadim,
I finished the HL7 FHIR basics page. Let me know what you think.
I also made a draft for the security page, but I am a little unsure what exactly needs to be stated here. It is now a very short statement. For example, the US code security page (http://hl7.org/fhir/us/core/security.html) is quite extensive on this topic, but I guess not really our scope. So let me know if this is enough or if we want to add more here.
> HL7 FHIR basics and Security page

- README.md
- input/fsh/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Terminology.fsh
This works around the issue of the form previewer not rendering them right -
> Move SNOMED codes out of the questionnaire

- input/fsh/Clinical-Response-01-Baseline.fsh
- input/fsh/Clinical-Response-02-6-Months.fsh
- input/fsh/Clinical-Response-03-Annual-Follow-Up-2.fsh
- input/fsh/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Patient-Reported-Response-02-6-Months.fsh
- input/fsh/Patient-Reported-Response-03-Year-1-and-2.fsh
- input/fsh/Patient-Reported-Response-04-Annual-Update.fsh
- input/fsh/Terminology.fsh
- input/fsh/debug-bundles.fsh
I've added in answerCoding instead of answerStrings into the baseline clinical response questionnaire. I've used UUIDs to create a CodeSystem. There are no errors or warnings, but the QA report does return many hints since the Codesystem is unknown and can therefore not be validated. As discussed previously, we will ignore this because it serves the purpose.
> Adding in answerCoding to Clinical Baseline

- input/fsh/Clinical-Response-01-Baseline.fsh
- input/fsh/Clinical-Response-02-6-Months.fsh
- input/fsh/Clinical-Response-03-Annual-Follow-Up-2.fsh
- input/fsh/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Patient-Reported-Response-02-6-Months.fsh
- input/fsh/Patient-Reported-Response-03-Year-1-and-2.fsh
- input/fsh/Patient-Reported-Response-04-Annual-Update.fsh
- input/fsh/Terminology.fsh
- input/fsh/debug-bundles.fsh
Hi Vadim,
I have some difficulties with the rendering of the value sets for race and ethnicity. There is no error from FSH, but in the SDC questionnaire app the answers aren't shown. But I don't know what I do wrong here, I've tried a lot of things without result. 
Another issue I have is that I don't know how to use the codes from the yes/no/unknown value set in an EnableWhen rule. This occurs in the question about axillary clearance in clinical responses 02 and 03. I also tried adding in the codesystem for the Yes answer, but this didn't work. Could you have a look at it?
Furthermore, I changed a lot of the naming of the value sets and code systems to make it more consistent and to ease reading the IG.
> Changing naming and some ValueSets

- input/fsh/Profiles clinical datapoints/Extensions.fsh
Per meeting on https://confluence.hl7.org/display/CIC/%28ICHOM%29+Breast+Cancer+PCOM+Set+FHIR+IG%2C+July+13th+2022
> Adjust race and ethnicity binding strength from required to example

- design-doctorine.md
See https://confluence.hl7.org/display/CIC/%28ICHOM%29+Breast+Cancer+PCOM+Set+FHIR+IG%2C+June+22nd+2022.
@MariekeSpanFurore add any notes you took in here as well.
> Update design decisions from June 22nd meeting

- design-doctorine.md
I've added that we deviate from mCODE in how we have modelled the TNM scores
> adding decisions regarding TNM stages

- design-doctorine.md
Clarify multidisciplinary meeting modelling per input from Christina Nielsen.
> Clarify multidisciplinary meeting modelling

- README.md
- input/fsh/Profiles clinical datapoints/Condition.fsh
- input/fsh/Profiles clinical datapoints/ListofAliases.fsh
- input/fsh/Profiles clinical datapoints/TreatmentVariables.fsh
- input/fsh/Questionnaires/Clinical-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Clinical-Response-02-6-Months.fsh
- input/fsh/Questionnaires/Clinical-Response-03-Annual-Follow-Up-2.fsh
- input/fsh/Questionnaires/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Patient-Reported-Response-03-Year-1-and-2.fsh
- input/fsh/Questionnaires/Rulesets.fsh
- input/fsh/Questionnaires/debug-bundles.fsh
- input/fsh/Terminology.fsh
This is the (draft) version of the treatment variables
> Model Treatment Variables

- input/fsh/Terminology.fsh
Correct some copy/paste errors
> Fix treatment plan not followed codesystem & valueset

- input/fsh/Profiles clinical datapoints/TumorFactors.fsh
- input/fsh/Terminology.fsh
I updated the molecular profiling profiles with custom codes. Now they also have correct examples and mappings.
> Update molecular profiling

- input/fsh/Profiles clinical datapoints/Condition.fsh
Rename Death BC profile to be more intuitive.
> Rename Death BC profile

- input/fsh/Profiles clinical datapoints/TumorStaging.fsh
Fix AJCC attribution to 8th edition - this is per the new annual update.
> Fix AJCC attribution to 8th edition

- input/fsh/Profiles clinical datapoints/DisutilityOfCare.fsh
- input/fsh/Profiles clinical datapoints/ListofAliases.fsh
Improve reoperation modelling use to use causedBy instead of partOf
> Improve reoperation modelling use to use causedBy

- input/fsh/Terminology.fsh
- input/includes/markdown-link-references.md
Fixed the errors in the QA report
> Fix errors code systems

- input/fsh/debug-definitions-bundle.fsh
- input/fsh/debug-examples-bundle.fsh
I've added two more bundles as requested. 1 with all definitions of the IG and 1 with all example resources.
> Adding 2 more debug bundles

- input/pagecontent/3_standard-set.md
Rename 'discrete resources' to profiles - per feedback at CIC.
> Rename 'discrete resources' to profiles

- input/fsh/Profiles clinical datapoints/TumorStaging.fsh
Based on this ticket: https://jira.hl7.org/browse/FHIR-38641
> Replace T-code in examples

- .github/workflows/blank.yml
- input/fsh/Profiles clinical datapoints/TumorFactors.fsh
Runs SUSHI on PRs, so we don't merge PRs that have SUSHI errors by accident.
> Add SUSHI validation to PRs

- input/fsh/Questionnaires/Clinical-Response-01-Baseline.fsh
- input/fsh/debug-bundles.fsh
Align it with the latest terminology.
> Update clinical baseline questionnaire to use 5.0 valuesets

- design-doctorine.md
We did not obtain the permission to publish the scoring algorithms publicly.
> Remove auto-scoring from questionnaires

- input/fsh/Profiles clinical datapoints/TreatmentVariables.fsh
- input/fsh/Questionnaires/Clinical-Response-02-6-Months.fsh
- input/fsh/Terminology.fsh
- input/fsh/debug-bundles.fsh
Questionnaire needs validation of:
* Value Set contents
* Enable when behavior against current spec Set
Please validate and then merge. We will add the auto-completion at a later date.
> Initial refactoring of the clinical response 6 mo

- input/fsh/Profiles clinical datapoints/TreatmentVariables.fsh
Had some feedback on whenever this is for an individual therapy session or for the overall treatment - hopefully ICHOM's description here in the profile itself will help.
> Clarify performed period for therapies

- input/fsh/Questionnaires/Clinical-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Clinical-Response-02-6-Months.fsh
- input/fsh/Questionnaires/Clinical-Response-03-Annual-Follow-Up-2.fsh
- input/fsh/Questionnaires/Eaxmple-Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Example-Clinical-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Patient-Reported-Response-02-Follow-Up.fsh
See: [BCFI-100](https://ichom.atlassian.net/browse/BCFI-100)
> Adjusting LinkIDs

- sushi-config.yaml
It took a lot of work to make that change!
> Fix jira spec artifacts error

- input/pagecontent/index.md
> Add download links and IP statements to homepage

- design-doctorine.md
- input/fsh/Profiles clinical datapoints/DisutilityOfCare.fsh
- input/fsh/Profiles clinical datapoints/TreatmentVariables.fsh
- input/fsh/Profiles clinical datapoints/TumorFactors.fsh
- input/fsh/Questionnaires/Clinical-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Clinical-Response-02-6-Months.fsh
- input/fsh/Questionnaires/Clinical-Response-03-Annual-Follow-Up-2.fsh
- input/fsh/Questionnaires/Eaxmple-Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Patient-Reported-Response-01-Baseline.fsh
- input/fsh/Questionnaires/Questionnaire BreastQ.fsh
- input/fsh/Questionnaires/Questionnaire EORTCQLQ.fsh
- input/fsh/Terminology.fsh
- input/fsh/debug-bundles.fsh
Changed numerical codes to letter codes to improve data handling and quality. Renamed some existing codes to be more intuitive out of the box.
> Change numerical codes to letter codes

- FHIR-ichom-breastcancer.xml
- publication-request.json
With the help of Lloyd I fixed the warning about the Jira specification.
> Fix warning

- input/fsh/Profiles clinical datapoints/BodyMeasures.fsh
fix error "The slice definition has min of 0 but add up to 1..."
> fix bodyweight/bodyheight slice error

- _updatePublisher.sh
- input/pagecontent/index.md
- sushi-config.yaml
updated title and added attribution notice to index.html @vadi2
> updated tittle and notice
